- name: Create a spot instance
  local_action:
    module: ec2
    aws_access_key: '{{ aws_access_key }}'
    aws_secret_key: '{{ aws_secret_key }}'
    id: '{{ instance_id }}'
    group: '{{namespace}}-security_group'
    instance_type: '{{ instance_type}}'
    image: '{{ ami_id }}'
    region: '{{ region }}'
    keypair: '{{ key_name }}'
    vpc_subnet_id: '{{ subnet_id }}'
    spot_price: '{{ spot_price }}'
    spot_wait_timeout: 300
    assign_public_ip: yes
    wait: true
    state: present
    count: 1
    volumes:
      - device_name: /dev/sda1
        volume_size: '{{ volume_size }}'
        delete_on_termination: true
  register: ec2
- name: Add new instance to host group
  add_host:
    hostname: '{{ item.public_ip }}'
    groupname: launched
  with_items: '{{ ec2.instances }}'
