- name: Create the OpenShift cluster-up script
  become: true
  shell: >
        export PUBLIC_IP={{hostvars['localhost']['ec2'].instances[0].public_ip}}

        export PUBLIC_HOSTNAME="master.{{public_dns_zone}}"

        export ROUTING_SUFFIX="{{public_subdomain_prefix}}.{{public_dns_zone}}"

        export NODE_ROOT=/opt/openshift

        export NODE_DATA=$NODE_ROOT/data

        export
        CLI_URL=https://storage.googleapis.com/origin-ci-test/branch-logs/origin/v3.7.0/builds/test_branch_origin_cross/1032/artifacts/zips/openshift-origin-client-tools-v3.7.0-7ed6862-linux-64bit.tar.gz

        # create the volume folders

        sudo mkdir -p $NODE_DATA/v1

        sudo mkdir -p $NODE_DATA/v2

        sudo mkdir -p $NODE_DATA/v3

        sudo mkdir -p $NODE_DATA/v4

        sudo chmod -R 777 $NODE_ROOT # FIXME care for proper permissions?


        # install the CLI

        curl -L -0 $CLI_URL | tar -zx -C /tmp

        cd /tmp/op* && sudo mv oc /usr/local && sudo ln -sf /usr/local/oc
        /usr/local/bin/oc


        # create the cluster script

        sudo echo "/usr/local/oc cluster up --public-hostname=$PUBLIC_HOSTNAME
        --routing-suffix=$ROUTING_SUFFIX --host-config-dir=$NODE_DATA/v1
        --host-data-dir=$NODE_DATA/v2 --host-pv-dir=$NODE_DATA/v3
        --host-volumes-dir=$NODE_DATA/v4 --use-existing-config=true
        --logging={{ openshift_logging }} --metrics={{ openshift_metrics }} --version={{ openshift_version }}" >>
        $NODE_ROOT/cluster_up

        sudo chmod +x $NODE_ROOT/cluster_up

- name: Start the OpenShift cluster
  shell: /opt/openshift/cluster_up
  become: true
  